REGEX_BREAK_PAR = r"[\n]"
REGEX_BREAK_LINE = r"\n\s*" #r"[\n]+\s"
REGEX_BREAK_BLOCK = r"(?=Câu \d+)"
REGEX_REMOVE_ADS = r"(Dành cho).*?(miễn phí)"
REGEX_CUT_ANSWER = r'(Chứng minh|Lời giải|Hướng dẫn trả lời|Chứng minh|Giải thích|Trả lời|Bài giải|Kết quả|Giải chi tiết|Bài làm).*?[:]'
REGEX_COMMAND_REMOVE = r'(Hãy|Mời|Nêu|Vui lòng|Xem thêm|Xin|Làm ơn|Please|Cảm ơn|Tra cứu|Thanks|Tạm biệt|Goodbye).*?[.?!:]'
TAG_PARENT_EXTRACT = ['div', 'main', 'article', 'section']
TEXT_POST_REMOVE = [
    'Đề bài',
    'Lời giải chi tiết',
    'Trả lời hay',
    'Lời giải của',
    'chi tiết khác: ',
    'Đáp án đúng'
]
TEXT_REMOVE = [
    'Mở trình đơn chính',
    'Đăng ký tư vấn',
    'Gửi thông tin',
    'Bài tập có liên quan',
    'Mục lục',
    'Quảng cáo',
    'Chia sẻ',
    'Bình chọn',
    'Thêm vào câu hỏi',
    'Đề bài',
    'VietJack',
    'Tải app',
    'Xem đáp án',
    'Xem thêm',
    'Xem đáp án',
    'Xem lời giải',
    'Lấy lại mật khẩu',
    'Đăng nhập',
    'Đăng ký',
    'Đăng xuất',
    'Nhập Email',
    'Trang chủ',
    'Trang trước',
    'Trang sau',
    'Trắc nghiệm',
    'các câu hỏi khác',
    'Nội dung bài viết',
    'LUYỆN TẬP TRẮC NGHIỆM'
    'TRUY CẬP NGAY',
    'XEM CHI TIẾT',
    'All Rights Reserved',
    'sửa mã nguồn',
    'sửa',
    'CÂU HỎI HOT CÙNG CHỦ ĐỀ',
    'Tìm kiếm',
    'Bài viết liên quan',
    'Lời giải của Tự Học 365',
    'GIÚP MÌNH NHANH NHÉ',
    'Xem bình luận',
    'Sửa đổi'
]

REGEX_TEXT_REMOVE = "|".join(TEXT_REMOVE)

REGEX_TEXT_POST_REMOVE = "|".join(TEXT_POST_REMOVE)

TAG_REMOVE = [
    'blockquote',
    'script',
    'style',
    'link',
    'noscript',
    'header',
    'footer',
    'nav',
    'aside',
    'input',
    'button',
    'select',
    'textarea',
    'iframe',
    'link',
    'table',
    'canvas',
    'a',
    'aside',
    'figure'
]

CLASS_REMOVE = [
    'color-orange font-roboto-b',
    'form-add-question',
    'section-footer',
    'popup-feedback',
    'footer-top',
    'content-how-do',
    'luotxem',
    'ngayarea',
    'rightpane',
    'toppath',
    'TOP_MARQUEE_MARQUEE',
    'vj-note',
    'adsenrl',
    'box-most-viewed',
    'toc-nav-item',
    'post-text',
    'toc-v2',
    'box-qaAdd',
    'share-qa',
    'votepost',
    'modally',
    'modally-content',
    'paging',
    'pc_tel',
    'more-post-edit',
    'more',
    'listpost_adsen',
    'tagstags',
    'authorpost',
    'customtext',
    'modally-init',
    'tab-content',
    'author-p',
    'catg-extend',
    'fb-share-button',
    'vj-breadcrumb',
    'search_google',
    'form-sta,'
    'same',
    'list-subject',
    'comment',
    'gg-ads',
    'content_method_container',
    'title-header cmt',
    'w3-sidebar',
    'box-link-post',
    'nextprev',
    'w3-clear',
    'copyright',
    'vj-detail-related',
    'vj-iframe',
    'load-more-comment,'
    'comment-list',
    'load-more',
    'qiauthor',
    'qiboxtincungchuyenmuc',
    'qifootermobile',
    'other-courses',
    'comment d-none d-lg-block',
    'meta',
    'footer',
    'f-info',
    'header',
    'sidebar',
    'meta-post',
    'navbar-brand',
    'counter-hierarchy',
    'wrapper has-toggler',
    'hidden-xs',
    'relatedposts',
    'box-taxbox',
    'tags',
    'i-tool',
    'sharelike',
    'box-toptuyensinh box_zunia_ads_ts',
    'list-content-chuong',
    'fs12',
    'posrelative',
    'nav',
    'navbar',
    'dropdown-menu',
    'is-hidden-mobile',
    'menu',
    'aside',
    'i-title',
    'related-title',
    'related-content',
    'related-links',
    'related-posts',
    'input',
    'an',
    'button',
    'contlink',
    'subheader',
    'heading-primary',
    'block-news-body',
    'tabs',
    'post-info',
    'toan_bo',
    'list-by-week',
    'list-news-related',
    'mauhead',
    'vn-tit-question',
    'sidebar__inner',
    'form-sta',
    'media',
    'snap-content',
    'footer_inner',
    'header_inner',
    'list-article-bottom',
    'bottom_cnt_ad',
    'other',
    'box_other',
    'card-footer',
    'control',
    'controls',
    'user-block',
    'vj-tag-container',
    'title-rating',
    'review',
    'content-rating',
    # 'clearfix',
    'list-categories',
    'question-verified',
    'header-container',
    'panel-body',
    'mgbox',
    'mgheader',
    'fb-root',
    'bg-white m-t-10 border-simple',
    'title-des3',
    'item-qa',
    'select',
    'textarea',
    'iframe',
    'link',
    'table',
    'page-header',
    'page-footer',
    'vector-header-container',
    'vector-menu-content',
    'vector-settings'
    'site-footer',
    'site-header',
    'box-share',
    'related-link',
    'related-posts',
    'related-posts-title',
    'related-posts-container',
    'related-posts-item',
    'section-content',
    'modal-dialog',
    'box-link-post',
    'qa-relates',
    'detail-title',
    'toc',
    'sidebar-toc',
    'w3-clear nextprev',
    'toolbox',
    'qa-wrapper',
    'countdown',
    'detail-action',
    'box_gray',
    'action',
    'fullname',
    'des-qa',
    'leftbar',
    'panel-body',
    'quiz-relate',
    'panel-group'
]

CLASS_PRIORITIZE = [
    'mw-parser-output',
    'loigiai',
    'answer',
    'accordion-detail',
    'answer-container',
    'anwsers-correct',
    'card-comment-content',
    'content_box',
    'box_content',
    'question-reason',
    'solution-item',
    'box-mes ipading',
    'main-container',
    'content-solution',
    'comment-author-kiemthecao'
]

COOKIE_LIST = [
    "NID=511=g3djHVlz8F7W7bMxfleZvJBWogmBERe3Q4eqOAggmCuazsuN4CNFu3sODRFXgVbcgcRlEa0qKnIm__4-zD2PEkLKVbVLQiHZwdkqGetAU8erHuut25dmtdsfCv2gUJIYHDTTXi8C8HaLoKxkN1KWb11c0_Dlld9GxfJguqDyqkM",
    "NID=511=ecfTHyOth6XUyhzRH3CB0rJifSvc2WFE724Thquo9sYQh5iaShRQDxwepFy636RUCetmsJ5PqZ99R_kuR_XxtEADEpFl7R3mEbbafEiY6DylSxoblaSRUqYsYSWWRsYKg8Arg29JRpMPghdzJNw5zaAR6m_1pE6ozqsA3vYmVvQ"
]

USERAGENT_LIST = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.0.0',
]